# Simple workflow for deploying static content to GitHub Pages
name: Deploy Vite to Github Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "yarn"

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn run build

      # Debug: Ensure your ./dist folder actually has files
      - name: List dist folder
        run: ls -la ./dist

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        # You can try @v2 or @v3, but some folks need @v3 to produce .tgz 
        # for the deploy-pages@v2 action to work correctly.
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./dist"
          # Optional: name your artifact explicitly
          artifact-name: "my-pages-artifact"

      - name: Deploy to GitHub Pages
        id: deployment
        # Most people use @v2 here
        uses: actions/deploy-pages@v2
